### ISSUE TITLE
Run dedop-core with Python 3.6

### ISSUE THREAD

**Issue by hans-permana** [DeDop/dedop-core#33]
Test dedop-core to run with Python 3.6. This is to enable using newer version of cate-util, which is about to migrate to Python 3.6.

- [x] Test CLI
- [x] Test webapi
- [x] Test Processors
- [x] Test Backend Installer

**Comment by hans-permana** [comment]
I created a new branch "python-36" in which I changed the environment.yml to use Python 3.6 and updated the dependencies respectively. I also did a quick test on the CLI and everything seems to work ok (I did config and workspace management, as well as running a process).

**Comment by mark-ep** [comment]
I've been running the unit tests in python3.6 and I've got two tests failing - for the inspect and compare scripts. In both cases it is because the module `bokeh.util.platform` does not have a function `is_notebook`.

Have you seen a similar issue at all @hans-permana ? It might well simply be a problem with the dedop/python installation in my test environment.

**Comment by forman** [comment]
@mark-ep So if we fix the missing `is_notebook` function, we can than move 3.6, right? This would be the cleanest solution for this issue.

**Comment by mark-ep** [comment]
yes this should fix the problem

**Comment by hans-permana** [comment]
Done in this merge https://github.com/DeDop/dedop-core/commit/c499e724eabbfed83b196eb25135515148b3d956. Tested with this procedure https://github.com/DeDop/dedop-core/wiki/DeDop-test-procedure-after-a-successful-build
